### ISSUE TITLE
January 2024 Newsletter

### ISSUE THREAD

**Issue by AlexandraAAJ** [the-turing-way/newsletter#1]
Newsletter is being drafted here: https://hackmd.io/@turingway/Sy7Ig8U9p

**Comment by AlexandraAAJ** [comment]
Content to include in the January Newsletter: 
- Promote the TTW Community Call on 15 Feb, include the link to register
- TTW Participation at Fosdem and State of Open Con
- Share BridgeAI Event: [AI governance: Key UK government initiatives and future direction](https://iuk.ktn-uk.org/events/ai-governance-key-uk-government-initiatives-and-future-direction/?utm_campaign=2428856_BridgeAI%20-%20ATI%20-%20Governance%20webinar&utm_medium=email&utm_source=dotdigital&dm_i=2VFU,1G248,8ZJ9N6,5QEMZ,1)

**Comment by aleesteele** [comment]
Accidentally duplicated with #6
