### ISSUE TITLE
March 2024 Newsletter

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/newsletter#12]
This is an issue for saving things for the next March 2024 newsletter!

Draft: https://hackmd.io/meW9cfW-RECaFmASAKCMBA

**Comment by aleesteele** [comment]
To add to newsletter:
- Book Dash participant application form + videos
- Next onboarding call
- Next community call

**Comment by aleesteele** [comment]
Talks in March
- 6 March (lLondon, UK/onilne/hybrid): Save the date for our Practitioners Hub Showcase Event featuring case studies, expert panels, and attend-led discussions – sign-up here!
- 12 March (online) - Join @Alejandro Coca-Castro at the Institute of Computing for Climate Science (ICCS)'s ReproHack!
- 19 - 20 March (London, UK): We'll have community members presenting The Turing Way at AI-UK over the two day event, sign up here!
- 22 March (online): @Emma Karoune and @Malvika Sharan will be doing a panel discussion at the Year of Open Science culmination conference
- 22 March (London, UK): @Anne Lee Steele will be giving a presentation at the Turing about The Turing Way for the Data-Centric Engineering Meeting

**Comment by AlexandraAAJ** [comment]
**Expression of interest form: The Turing Way Practitioners Hub – 2024/2025 cohort**

🚀 The Turing Way Practitioners Hub is inviting Expressions of Interest from organisations and SMEs engaged in data science and AI to join its second cohort of Experts in Residence (EiRs). With a focus on implementing best practices in data science and AI initiatives in their own organisations, practitioners from various sectors will engage in this cohort-based programme between September 2024 and February 2025.

📅 Apply by 30 May 2024
🎫 Register here: [IUK KTN](https://iuk.ktn-uk.org/opportunities/turing-way-practitioners-hub-become-an-expert-in-residence/)

🌐 Experts in Residence will have the opportunity to engage with other domain experts, exchange knowledge and build a long-term strategy for scaling their efforts using industry best practices in data science and AI. They will be supported to implement open source, open data, cross-sector collaboration, research reproducibility and ethical approaches in their organisation’s workflow, enhancing the quality, viability and real-world impact of AI technologies through their work.
💬 The Turing Way Practitioners Hub, supported by Innovate UK BridgeAI, is more than a forum—it's a dynamic space for industry practitioners to collaborate on cutting-edge open AI and data science practices.

Don't miss out on to express your interest in being a part of the second Cohort!

**Comment by aleesteele** [comment]
Congratulations, The Turing Way (10953) has been approved as a digital public good (DPG)!

We are excited to share that it is now listed on the [DPG Registry](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdigitalpublicgoods.net%2Fregistry%2F&data=05%7C02%7Casteele%40turing.ac.uk%7C97b09922731f4da9174508dc4c2b8e53%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638468997173398513%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=mS5XQfml%2B7I%2BtKmPQvF8gYNg2wJMlFue3VFvRmHiWPQ%3D&reserved=0) in addition to a growing network of catalogs and aggregated lists of digital public goods. 

DPG status will be valid for one year. We will send you a reminder to renew your status. This is to ensure that your solution continues to be in compliance with the latest [Digital Public Goods Standard](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdigitalpublicgoods.net%2Fstandard%2F&data=05%7C02%7Casteele%40turing.ac.uk%7C97b09922731f4da9174508dc4c2b8e53%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638468997173398513%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=VFEebhxDTLJOar1HSG0iAsbeU65h1ttrziK9Wmch9ns%3D&reserved=0).

For many new DPGs, this is an exciting milestone to share with their community. Linked [here](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1ypYG1EPY7_GXxnFwrhPPlXviKNPWOdJPacE0CaUQx6Q%2Fedit%3Fusp%3Dsharing&data=05%7C02%7Casteele%40turing.ac.uk%7C97b09922731f4da9174508dc4c2b8e53%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638468997173398513%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=93sPSSHF0Fhnc52ifJx3B8POqzJjxBkARs5oyCoFkio%3D&reserved=0) is a communications guide that can help you announce your DPG status. Included in this email are Jameson and Sarah from our communications team that would be more than happy to support if you have any questions.

You will also be added to our community of product owners, where you can join our community calls and receive an exclusive newsletter connecting you to valuable resources. Please let us know if other colleagues from your organization/project might be interested in being added to the community channels and activities.

We thank you for your interest in supporting digital public goods and look forward to continuing to watch the impact your project will make.
