### ISSUE TITLE
April 2024 Newsletter

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/newsletter#13]
Please add things you would like to add to the April 2024 newsletter here, whether that's:
- Events or talks where you featured or talked about The Turing Way
- Roles, opportunities, and/or jobs that others can apply for
- Community updates and other news
- Pull requests or issues you'd like to feature or plug for others to get involved in

Draft is enclosed here: https://hackmd.io/We6JczMiQH2VU87YaMtLQg?both

**Comment by AlexandraAAJ** [comment]
HI Anne, please add the following at the April Newsletter:

**The Turing Way Practitioners Hub Showcase Event - Video recording**
On the 6th of March The Turing Way hosted the The Turing Way Practitioners Hub Showcase event. A full day hybrid event to talk about **Co-adoption of AI and Open Practices* for Innovation**, featuring panels, a fireside chat, case studies series and the launch of the Expression of interest to join the second cohort of Experts in residence. 
If you missed it, you can watch the recordings here: (Can you create a playlist with the 4 videos together?) 
- Panel 1: Demystifying AI and Open Practices for SMEs: https://youtu.be/1SrmZ-hPqsE
- Fireside Chat with Amanda Brock (OpenUK): https://youtu.be/Ri4WImyUj00
- The Practitioners Hub - Case Studies Series: https://youtu.be/Hotwg9DkHgk
- Panel 2: AI and Open Practices in Emerging Sectors: https://youtu.be/Jisq1UE4Gfc

**Expression of Interest (EoI) Forms to Join the Second Cohort - 2024 are now open!**

**EoI for SMEs and organisations** 
We are inviting SMEs and organisations engaged in data science and AI to share their interest in joining our second cohort of Experts in Residence (EiRs). With a focus on implementing best practices in data science and AI initiatives in their own organisations, practitioners from various sectors will engage in this cohort-based programme between September 2024 and February 2025. 

**EoI to join a network of Advisors** 
We are also accepting interest from individuals to join our network of advisors who will engage with our project and cohort activities. Advisors will bring real-world expertise that can benefit SMEs interested in implementing best practices in data science and AI initiatives in their organizations.

EoI will be open till the 30 May, here: https://www.turing.ac.uk/turing-way-practitioners-hub

The Practitioners Hub is a forum for cross-sector collaboration, knowledge exchange and strategic partnerships for accelerating the co-adoption of AI and best practices. To learn more about the Practitioners Hub and to explore outputs from the first cohort from 2023, please visit https://www.turing.ac.uk/turing-way-practitioners-hub.

**Comment by aleesteele** [comment]
Senior Research Community Manager - People in Data: https://cezanneondemand.intervieweb.it/turing/jobs/senior-research-community-manager-people-in-data-42030/en/

**Comment by aleesteele** [comment]
Flagged by @AndreaSanchezTapia: 

The research and innovation team at Global Fishing Watch :fishing_pole_and_fish: :earth_americas: has two data science open positions:
Data Scientist, Vessel Tracking and Behavior (Remote) https://boards.greenhouse.io/globalfishingwatch/jobs/5942158003
Senior Data Scientist, Remote Sensing & Data Fusion https://boards.greenhouse.io/globalfishingwatch/jobs/5942178003
Apply even if you think you don’t check all the boxes, but believe you have unique skills that make you a great fit for the role :two_hearts: (And please resend to your contacts! :pray: )

**Comment by aleesteele** [comment]
Flagged by Bri Johns from the GOSH Community
![gosh ambassador program social media](https://github.com/the-turing-way/newsletter/assets/18509789/1764db74-2f50-4b7e-a896-4fa008009519)
> The GOSH Community is ex
cited to announce the inaugural call for applications for the GOSH Ambassador Program! This initiative seeks to empower and expand our community of researchers, educators, and practitioners passionate about promoting open science hardware principles. We will accept both applications and nominations for candidates you think would make great open science hardware ambassadors. Find out more about the program and apply [here](https://openhardware.science/gosh-ambassador-program/). Applications close May 15th!

**Comment by AlexandraAAJ** [comment]
💻 Free live training on the Turing Online Learning Platform: **Operationalising Ethics in AI** for the agriculture, construction and transport sectors. 

🎓 What do the live training sessions cover? Learn to develop AI that adheres to ethical standards and aligns with societal values. Focused on applied transparency and fairness in real-world AI deployment, this practical course empowers you to integrate ethical principles into the AI systems design process through real-world case studies and hands-on activities. 

👥 Who can apply to attend? Open to participants from small and medium enterprises (SMEs) based in the UK, this live training is ideal for those developing or using AI solutions – or looking to employ them in their organisations. There are no prerequisite skills required, but an interest in AI and basic understanding of the regulatory landscape is beneficial. Details: 
🌟 10am – 1pm across two days 
🌟 Hosted virtually 
🌟 Expert-led 
🌟 Meaningful discussion with experts and peers. 

Find tailored sessions on different dates for the following industries: 
❇️ Agriculture:  Thursday 2 May, 2024, Thursday 9 May, 2024 
❇️ Construction: Thursday 16 May, 2024, Thursday 23 May, 2024 
❇️ Transport sector: Thursday 30 May, Thursday 6 June 2024

Find out more and register here: https://iuk.ktn-uk.org/opportunities/operationalising-ethics-for-the-creative-industries-live-training-course-the-alan-turing-institute/

**Comment by aleesteele** [comment]
Thanks everyone! Adding in these notes - @AlexandraAAJ in particular, here's the playlist you can use: https://www.youtube.com/watch?v=1SrmZ-hPqsE&list=PLBxcQEfGu3DlKTu6uCXRZ2tyA62VZWaUz 😊

**Comment by aleesteele** [comment]
So I wanted to share that my colleague and I have a an 8-week learning series on community stewardship coming up this fall. The series aims to support those who organize large groups of people around a common mission or goals.
If you want to learn more about this, you are welcome to join us for a free 1-hour “taster” sessions on [August 20](https://www.eventbrite.com/e/taster-a-learning-community-for-community-stewards-tickets-881158377427) or [September 13](https://www.eventbrite.com/e/taster-a-learning-community-for-community-stewards-tickets-881160062467).
Or, you can dive right in by:
-> Joining the session that is [open to the public](https://www.eventbrite.com/e/a-learning-community-for-community-stewards-tickets-881141165947)
-> Bringing us to your site with an [in-house learning session](https://drive.google.com/file/d/1QlpyySckKLqUC1SZeBuCRORDCQmdfZl4/view)
