### ISSUE TITLE
May 2024 Newsletter

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/newsletter#14]
Please add things you would like to add to the May 2024 newsletter here, whether that's:
- Events or talks where you featured or talked about The Turing Way
- Roles, opportunities, and/or jobs that others can apply for
- Community updates and other news
- Pull requests or issues you'd like to feature or plug for others to get involved in

Draft is enclosed here: https://hackmd.io/hARwOXXtTWCQGliotgfOQA

**Comment by aleesteele** [comment]
Moving to our May newsletter - featuring some sticker (re-designs):

Thank you to Anna Zanchetta (@ciupava), David Sarmiento-Perez (@AlexandraAAJ), Esther Plomp (@EstherPlomp), Jim Madge (@JimMadge)and many others for contributing to the discussion and (re-)designing of our stickers and logo more designs welcome! [Join the slack discussion](https://theturingway.slack.com/archives/C014KE9A9LM/p1713440903752039) and share your designs!

**Comment by aleesteele** [comment]
Collaborations Workshop updates – from the 5th anniversary (complete with photos!)

**Comment by mishkanemes** [comment]
https://www.ucl.ac.uk/advanced-research-computing/events/2024/jun/festival-digital-research-scholarship

**Comment by aleesteele** [comment]
Github training session: https://turing-uk.zoom.us/meeting/register/tJwvf--srDIoGNEwAt1xqyoJq-c0wUUdV2Ki

June Onboarding session: https://turing-uk.zoom.us/meeting/register/tJModOGrrjsqGNBzlCAk1vTzQodlkji6zl6E

**Comment by aleesteele** [comment]
apply before 15 July to attend the workshops: https://surveys.osc.lmu.de/OpenScienceSummerSchool2024
