### ISSUE TITLE
June 2024 Newsletter

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/newsletter#15]
Please add things you would like to add to the June 2024 newsletter here, whether that's:
- Events or talks where you featured or talked about The Turing Way
- Roles, opportunities, and/or jobs that others can apply for
- Community updates and other news
- Pull requests or issues you'd like to feature or plug for others to get involved in

Draft is enclosed here: https://hackmd.io/Qqrcg2RIQVawMQIrxDIRbg?both

**Comment by aleesteele** [comment]
Book Dash review

**Comment by AbcSxyZ** [comment]
Interested to potentially share work related to the meaning of open source, at least to inform and perhaps involve people. Related to https://github.com/the-turing-way/the-turing-way/pull/3705 (PR) + https://github.com/the-turing-way/the-turing-way/issues/3653 (original issue).

What should be the process to contribute to the newsletter ?

**Comment by aleesteele** [comment]
Community Forum - 11 July

**Comment by aleesteele** [comment]
@AbcSxyZ - thanks for commenting! This issue is for keeping track of news from within our community, and information that people would like to plug for the newsletter.

People can share everything from upcoming events, to issues and pull requests (as you have done) to anything else they would like to feature that is related to The Turing Way. Are you currently subscribed to our newsletter? You can do so here, to see more of what we feature: https://buttondown.email/turingway/

I think in terms of this discussion you plugged – I would gently suggest that you join an already existing space within our community before we plug the issue & discussion explicitly in our newsletter. It looks like there's already a lot of engagement on those issues, as well as a few gentle corrections, nudges, and guidance that have been made to you. I would advocate that we work on addressing those, especially as they have been made by community leaders who have already volunteered their time and thought to your work first. Then we can think about adding more voices added to the chorus via the newsletter. Does that sound okay to you?

During the August newsletter, as it is a slower month for community activities and within the community, we may have more issues & pull requests featured for folks. So you can keep that in mind - hope that helps!

**Comment by AbcSxyZ** [comment]
I saw the proposal and took the opportunity to try to invite more people to the party ! Thought it could be great prior to a potential merge to have more experts eyes with their feedback, some of your networks could be even more specialised regarding this question, but of course we can just share it when(/if) it's merged to share this state regarding the meaning of the concept.

Why not wait a while for developments and share this over the summer period, perhaps people will have a little more time to think, while maybe using others spaces like Slack. By curiosity if you don't mind, do you have subscribers with an email ending by "opensource.org" ?
