### ISSUE TITLE
September 2024 Newsletter

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/newsletter#19]
Please add things you would like to add to the September 2024 newsletter here, whether that's:
- Events or talks where you featured or talked about The Turing Way
- Roles, opportunities, and/or jobs that others can apply for
- Community updates and other news
- Pull requests or issues you'd like to feature or plug for others to get involved in

Draft is enclosed here: https://hackmd.io/a_g223o0TOq7Bt5sbIK34w?both

**Comment by aleesteele** [comment]
Spotlight series from Turing https://www.turing.ac.uk/data-science-and-ai-careers-spotlight-series/spotlight-series

**Comment by aleesteele** [comment]
Community Forum: https://github.com/the-turing-way/the-turing-way/issues/3815

**Comment by aleesteele** [comment]
New chapter announcement: https://hackmd.io/KPSQxvWoTp2CSy5Vz4rYqw?both

**Comment by malvikasharan** [comment]
NASA TOPS 101 training by OLS's Nebula:
:loudspeaker: Hi everyone! The OLS team is very excited to announce that registration is open for our next cohort of the[ OLS-NASA Nebula Program](https://openlifesci.org/nebula) - help us with spreading the news or register yourself!
:star: The program is 6-weeks long and covers the[ Open Science 101 Curriculum](https://nasa.github.io/Transform-to-Open-Science/) with hands-on learning and coaching. This is perfect for individuals or teams taking their first steps in open science and who want expert support with any aspect of their research: data, code or publications.
:date: The cohort runs from October 21 to November 29.
:admission_tickets: The last day to apply for a fee waiver is October 7. Please don’t hesitate to request a fee waiver – this is strongly encouraged!
:link: Register here: https://events.humanitix.com/ols-nebula.
:link: Fee waiver request: https://forms.gle/VV453jezChtK4cUG6
Feel free to contact my colleague Irene Ramos ([irene@we-are-ols.org](mailto:irene@we-are-ols.org)) with any questions :rocket:

**Comment by AlexandraAAJ** [comment]
AI Insight Chat Series: Is Open Source the future of AI?
🚀 Is Open Source the future of AI? 
 
Join @Innovate Uk BridgeAI programme partners, @The Alan Turing Institute on 24 October for an exciting panel discussion tailored for UK small and medium-sized enterprises (SMEs) as they explore the critical question: Is Open Source the Future of AI? 
 
- How can open-source AI offer flexibility, foster collaboration, and reduce costs? 
- What are the risks and challenges of open-source adoption, and how can SMEs overcome them? 
-  How can open-source AI drive innovation and help SMEs compete in a global market? 
- What real-world examples can guide your AI strategy and decisions?  
 
Whether you're new to AI or looking to enhance your existing strategy, this session will offer valuable takeaways to guide your decisions. 
 
<img width="742" alt="Is Open Source the future of AI 2" src="https://github.com/user-attachments/assets/9e27e2b5-0ea9-4b42-9b0a-be8ffbfa649e">

Don’t miss out on this opportunity to stay ahead in the AI game! 
Registration link: https://www.turingevents.co.uk/turingevents/frontend/reg/thome.csp?pageID=168326&eventID=400&CSPCHD=000001000000WIErm42QeWyloglloouvu7zRBQmQmxS8jJUXz_

**Comment by LelleDi** [comment]
New item for newsletter: [Open Source, Ethics & Innovation in AI  |  A Turing Way Practitioners Hub Event](https://www.eventsforce.net/turingevents/388/home) -I will follow up with copy for invite once reviewed by MS

**Comment by aleesteele** [comment]
Book Dash - extended deadline - duel language in Spanish/English

**Comment by aleesteele** [comment]
New chapter announcement: Data Missingness

**Comment by aleesteele** [comment]
And of course, welcoming @LelleDi to the team, adding that to our draft (will confirm on Monday)
