### ISSUE TITLE
January 2024 Newsletter

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/newsletter#6]
### Summary

Draft here: https://hackmd.io/taW4bjtpQ4-E2u_KsquI1A?both

- Announcing switch to Button down (platform for newsletter)
- ~~Announcing switch to quick weekly digest~~
- Community call on Feb 15
- Onboarding call on 31 January

**Comment by malvikasharan** [comment]
Please include this in the February newsletter: https://github.com/the-turing-way/the-turing-way/issues/3518.

We should include this in the Community Call to get some more people chiming in!
