### ISSUE TITLE
February 2024 Newsletter

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/newsletter#7]
This is an issue for saving things for the next February 2024 newsletter!

Draft here: https://hackmd.io/ny5XPNp6Rby28mAiml5ohQ?both

**Comment by aleesteele** [comment]
- Planning for 5 years of TTW: https://github.com/the-turing-way/the-turing-way/issues/3518
- @malvikasharan's feature: https://diginomica.com/why-do-no-harm-principle-can-be-key-open-source-sustainability-and-equality
- Book Dash images release
- Two new chapters: Electronic Notebooks & Data Hazards

**Comment by AlexandraAAJ** [comment]
- Co-adoption of AI and Open Practices for Innovation, The Practitioners Hub Showcase event on 6 March
- Book Dash: dates, application for local hub and planning committee
- Community Call recording
- AIUK

**Comment by aleesteele** [comment]
Adding Pen's talk from FOSDEM Open Research ORDEN: https://zenodo.org/records/10643358

**Comment by aleesteele** [comment]
@malvikasharan's feature on Sustain: https://podcast.sustainoss.org/221
